{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fireblockssdk\/fullkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fireblockssdk\/fullkey"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject","doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP","doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/Se","doc:\/\/com.fireblocks.Fireblocks\/SE","doc:\/\/com.fireblocks.Fireblocks\/SQ","doc:\/\/com.fireblocks.Fireblocks\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Information about the FullKey generated"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"}],"title":"FullKey","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FireblocksSDK@objc(cs)FullKey","modules":[{"name":"FireblocksSDK"}],"navigatorTitle":[{"kind":"identifier","text":"FullKey"}]},"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/algorithm","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/error","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/keyId","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/privateKey","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/publicKey"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/description()"]}],"references":{"doc://com.fireblocks.Fireblocks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP"},"doc://com.fireblocks.Fireblocks/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/Se"},"doc://com.fireblocks.Fireblocks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/keyId":{"role":"symbol","title":"keyId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/keyId","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/fullkey\/keyid"},"doc://com.fireblocks.Fireblocks/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SE"},"doc://com.fireblocks.Fireblocks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/fullkey\/init(from:)"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/description()":{"role":"symbol","title":"description()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/description()","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/fullkey\/description()"},"doc://com.fireblocks.Fireblocks/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","title":"FireblocksSDK","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FireblocksError","preciseIdentifier":"s:13FireblocksSDK0A5ErrorV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/error","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/fullkey\/error"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/privateKey":{"role":"symbol","title":"privateKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/privateKey","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/fullkey\/privatekey"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey":{"role":"symbol","title":"FullKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"}],"abstract":[{"type":"text","text":"Information about the FullKey generated"}],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FullKey"}],"url":"\/documentation\/fireblockssdk\/fullkey"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/algorithm":{"role":"symbol","title":"algorithm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"algorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Algorithm","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/algorithm","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/fullkey\/algorithm"},"doc://com.fireblocks.Fireblocks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SQ"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/publicKey":{"role":"symbol","title":"publicKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/publicKey","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/fullkey\/publickey"},"doc://com.fireblocks.Fireblocks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SH"},"doc://com.fireblocks.Fireblocks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FullKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FullKey"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FullKey"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/title","value":"FullKey"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/fragments","value":[{"kind":"identifier","text":"FullKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}