{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyDescriptor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fireblockssdk\/keydescriptor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fireblockssdk\/keydescriptor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject","doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP","doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/Se","doc:\/\/com.fireblocks.Fireblocks\/SE","doc:\/\/com.fireblocks.Fireblocks\/SQ","doc:\/\/com.fireblocks.Fireblocks\/SH","doc:\/\/com.fireblocks.Fireblocks\/s12IdentifiableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyStatus for each key"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyDescriptor"}],"title":"KeyDescriptor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FireblocksSDK@objc(cs)KeyDescriptor","modules":[{"name":"FireblocksSDK"}],"navigatorTitle":[{"kind":"identifier","text":"KeyDescriptor"}]},"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/algorithm","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/keyId","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/keyStatus"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/description()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/Identifiable-Implementations"],"generated":true}],"references":{"doc://com.fireblocks.Fireblocks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SH"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/description()":{"role":"symbol","title":"description()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/description()","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keydescriptor\/description()"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keydescriptor\/init(from:)"},"doc://com.fireblocks.Fireblocks/s12IdentifiableP":{"type":"unresolvable","title":"Swift.Identifiable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s12IdentifiableP"},"doc://com.fireblocks.Fireblocks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SQ"},"doc://com.fireblocks.Fireblocks/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SE"},"doc://com.fireblocks.Fireblocks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor":{"role":"symbol","title":"KeyDescriptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyDescriptor"}],"abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyStatus for each key"}],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyDescriptor"}],"url":"\/documentation\/fireblockssdk\/keydescriptor"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/Identifiable-Implementations":{"role":"collectionGroup","title":"Identifiable Implementations","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/Identifiable-Implementations","kind":"article","type":"topic","url":"\/documentation\/fireblockssdk\/keydescriptor\/identifiable-implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/algorithm":{"role":"symbol","title":"algorithm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"algorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Algorithm","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/algorithm","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keydescriptor\/algorithm"},"doc://com.fireblocks.Fireblocks/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/Se"},"doc://com.fireblocks.Fireblocks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP"},"doc://com.fireblocks.Fireblocks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","title":"FireblocksSDK","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/keyId":{"role":"symbol","title":"keyId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/keyId","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keydescriptor\/keyid"},"doc://com.fireblocks.Fireblocks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/keyStatus":{"role":"symbol","title":"keyStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyStatus","preciseIdentifier":"s:13FireblocksSDK9KeyStatusO"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/keyStatus","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keydescriptor\/keystatus"},"doc://com.fireblocks.Fireblocks/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"KeyDescriptor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"KeyDescriptor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"KeyDescriptor"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyDescriptor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/title","value":"KeyDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/fragments","value":[{"kind":"identifier","text":"KeyDescriptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}