{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryBlock"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tryBlock"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSException","preciseIdentifier":"c:objc(cs)NSException"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fireblockssdk\/tryblock(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fireblockssdk\/tryblock(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/tryBlock(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryBlock"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSException","preciseIdentifier":"c:objc(cs)NSException"},{"kind":"text","text":"?"}],"title":"tryBlock(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:ObjectiveCUtils.h@F@tryBlock","modules":[{"name":"FireblocksSDK"}],"navigatorTitle":[{"kind":"identifier","text":"tryBlock"}]},"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK"]]},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/tryBlock(_:)":{"role":"symbol","title":"tryBlock(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryBlock"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSException","preciseIdentifier":"c:objc(cs)NSException"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/tryBlock(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tryBlock"}],"url":"\/documentation\/fireblockssdk\/tryblock(_:)"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","title":"FireblocksSDK","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"tryBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tryBlock"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSException","preciseIdentifier":"c:objc(cs)NSException"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tryBlock"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tryBlock"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1tryBlock(_:)\/title","value":"tryBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1tryBlock(_:)\/fragments","value":[{"kind":"identifier","text":"tryBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}