{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyRecovery"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/fireblockssdk\/keyrecovery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/fireblockssdk\/keyrecovery"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject","doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP","doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/Se","doc:\/\/com.fireblocks.Fireblocks\/SE","doc:\/\/com.fireblocks.Fireblocks\/SQ","doc:\/\/com.fireblocks.Fireblocks\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyRecovery"}],"title":"KeyRecovery","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FireblocksSDK@objc(cs)KeyRecovery","modules":[{"name":"FireblocksSDK"}],"navigatorTitle":[{"kind":"identifier","text":"KeyRecovery"}]},"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/algorithm","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/keyId","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/keyRecoveryStatus"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/description()"]}],"references":{"doc://com.fireblocks.Fireblocks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP"},"doc://com.fireblocks.Fireblocks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SH"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/keyId":{"role":"symbol","title":"keyId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/keyId","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keyrecovery\/keyid"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","title":"FireblocksSDK","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk"},"doc://com.fireblocks.Fireblocks/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"},"doc://com.fireblocks.Fireblocks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SQ"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keyrecovery\/init(from:)"},"doc://com.fireblocks.Fireblocks/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SE"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/algorithm":{"role":"symbol","title":"algorithm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"algorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Algorithm","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/algorithm","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keyrecovery\/algorithm"},"doc://com.fireblocks.Fireblocks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP"},"doc://com.fireblocks.Fireblocks/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/Se"},"doc://com.fireblocks.Fireblocks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery":{"role":"symbol","title":"KeyRecovery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyRecovery"}],"abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyRecovery"}],"url":"\/documentation\/fireblockssdk\/keyrecovery"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/keyRecoveryStatus":{"role":"symbol","title":"keyRecoveryStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyRecoveryStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyRecoveryStatus","preciseIdentifier":"s:13FireblocksSDK17KeyRecoveryStatusO"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/keyRecoveryStatus","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keyrecovery\/keyrecoverystatus"},"doc://com.fireblocks.Fireblocks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/description()":{"role":"symbol","title":"description()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/description()","kind":"symbol","type":"topic","url":"\/documentation\/fireblockssdk\/keyrecovery\/description()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"KeyRecovery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"KeyRecovery"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"KeyRecovery"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyRecovery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/title","value":"KeyRecovery"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/fragments","value":[{"kind":"identifier","text":"KeyRecovery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}